#    SPDX-License-Identifier: Apache License 2.0
#
#    SPDX-FileCopyrightText: 2022 Western Digital Corporation or its affiliates.
#
#    Author: Jaco Hofmann (jaco.hofmann@wdc.com)

mkdir -p releases
make SIM_TYPE=VERILOG BRAM_SIM=1 OX_11_MODE=0 OMNIXTEND_CONNECTIONS=4 MAXIMUM_PACKET_SIZE=1500 MAXIMUM_TL_PER_FRAME=1 ip
cp build/ip/OmnixtendEndpoint_RES_15_RESTO_21_ACKTO_12_OX11_0_MAC_0_CON_4_MAXFRAME_1500_MAXTLFRAME_1_BRAMSIM_1.zip releases/
make SIM_TYPE=VERILOG BRAM_SIM=1 OX_11_MODE=1 OMNIXTEND_CONNECTIONS=4 MAXIMUM_PACKET_SIZE=9000 MAXIMUM_TL_PER_FRAME=64 ip
cp build/ip/OmnixtendEndpoint_RES_15_RESTO_21_ACKTO_12_OX11_1_MAC_0_CON_4_MAXFRAME_9000_MAXTLFRAME_64_BRAMSIM_1.zip releases/
make SIM_TYPE=VERILOG BRAM_SIM=0 OX_11_MODE=0 OMNIXTEND_CONNECTIONS=8 MAXIMUM_PACKET_SIZE=1500 MAXIMUM_TL_PER_FRAME=1 ip
cp build/ip/OmnixtendEndpoint_RES_15_RESTO_21_ACKTO_12_OX11_0_MAC_0_CON_8_MAXFRAME_1500_MAXTLFRAME_1_BRAMSIM_0.zip releases/
make SIM_TYPE=VERILOG BRAM_SIM=0 OX_11_MODE=1 OMNIXTEND_CONNECTIONS=8 MAXIMUM_PACKET_SIZE=9000 MAXIMUM_TL_PER_FRAME=64 ip
cp build/ip/OmnixtendEndpoint_RES_15_RESTO_21_ACKTO_12_OX11_1_MAC_0_CON_8_MAXFRAME_9000_MAXTLFRAME_64_BRAMSIM_0.zip releases/